language: rust
cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

os: linux

env:
  global:
    - CRATE_NAME="kp"

addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3
    - xorg-dev
    - libx11-xcb-dev
    - libgl1-mesa-dev

jobs:
  include:
    - name: "Linux with X11 clipboard suppport"
      env:
      - TARGET=x86_64-unknown-linux-gnu
      - SUFFIX="-x86_64-linux"

    - name: "Linux static binary without clipboard support"
      env:
      - TARGET=x86_64-unknown-linux-musl
      - FEATURES="--no-default-features"
      - SUFFIX="-x86_64-linux-no-clipboard"
      install:
      - rustup target add x86_64-unknown-linux-musl

    - name: "OSX with clipboard support"
      os: osx
      env:
      - TARGET=x86_64-apple-darwin
      - SUFFIX="-x86_64-osx"

before_install:
  - set -e
  - rustup self update

install: skip

script:
  - cargo rustc --release --target $TARGET $FEATURES -- -Clto -Copt-level=s -Cembed-bitcode=yes

before_deploy:
  # smoke test
  - echo 'P@ssw0rd' | target/$TARGET/release/$CRATE_NAME -d tests/chacha_argon_keyfile_pwd_gzip.kdbx -k tests/secret bar | xargs -I% test % = "BarPassword3"
  # archive
  - tar -C target/$TARGET/release -czf $CRATE_NAME-$TRAVIS_TAG$SUFFIX.tar.gz $CRATE_NAME

deploy:
  provider: releases
  token:
    secure: "W9c+FJ2oEY/XMAiUpepFIblZVt5Jew0m7igdE2p+uB9bJRLBjYTu47zD6vbtQDPjw1gLsaGutXenULOULwOzfoDaRxFlHP9j40QrIUwawBAMW/i7BQaCMS2XVc7bDc89jZPoii1yxdO/5KRDynhZjp4Q0i6XbYeYUwkVeGI0kBe0fhV6/wJD+j+i6DJS+ln8P0JWHvWUQiQ8D9nCkm4216xoWF080jnBbSUZl+vWYJz9RUy6GQCoY8y/mPMn8a3wYVgZ4jZ0HEXQKYCRke8ogYuPrJ+7sg6KVN74F20EF/QMEltuK9oBn9Zo8zkX6DBLvFwkw44c6dfMPQWgkR4TWQeT/ff4o/nfV0Negh5uSbPP8w2SrJzuiUq/GhOK0eXCkpfgtB2KAmiCPZyKjKCCaGxRO5oo8JWQhMZmXWvg5BQuDZgzzo7Ow2j/vY7i/5xMNugt31nvFSBJr8rukfCVJD6/zV3eJuwQArAxcuiORDhXS5IF/KP47yoOBdb6aYea+LkiIKDvT2ef+bAlO6jS9IFJKHpHksbvQve6md1iuIqDPtPZh+qEuZK/Z/yqPanakxev1mLT0afkwT0SdSX9b5V/yt3yYt5m6X/LS77V3WnaeJPhLg1ccS3mLY324uKYHQZC0e2jFZks0GBbP8IcqsYUA73yxrjtBs6hCCC4lZg="
  file: $CRATE_NAME-$TRAVIS_TAG$SUFFIX.*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
