[package]
name = "kp"
version = "0.1.0"
authors = ["paul <paul@makovi.ch>"]
edition = "2018"

[dependencies]
atty = "0.2"
clipboard = "0.5.0"
ctrlc = { version = "3.0", features = ["termination"] }
docopt = "1"
env_logger = "0.7.1"
kdbx4 = "0.4"
keyring = "0.7.0"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_warn"] }
rpassword = "4.0"
serde = "1.0"
serde_derive = "1.0"
skim = "0.6.9"
